export const loadBigHeads = () => [
  {
    id: 1,
    content: {
      accessory: "roundGlasses",
      body: "chest",
      circleColor: "blue",
      clothing: "vneck",
      clothingColor: "black",
      eyebrows: "concerned",
      eyes: "content",
      faceMask: true,
      faceMaskColor: "red",
      facialHair: "none3",
      graphic: "none",
      hair: "bob",
      hairColor: "white",
      hat: "none3",
      hatColor: "white",
      lashes: false,
      lipColor: "pink",
      mask: true,
      mouth: "open",
      skinTone: "brown",
    },
  },
  {
    id: 2,
    content: {
      accessory: "none",
      body: "chest",
      circleColor: "blue",
      clothing: "vneck",
      clothingColor: "red",
      eyebrows: "concerned",
      eyes: "dizzy",
      faceMask: true,
      faceMaskColor: "green",
      facialHair: "none",
      graphic: "redwood",
      hair: "balding",
      hairColor: "blonde",
      hat: "none2",
      hatColor: "green",
      lashes: true,
      lipColor: "purple",
      mask: true,
      mouth: "grin",
      skinTone: "red",
    },
  },
  {
    id: 3,
    content: {
      accessory: "roundGlasses",
      body: "chest",
      circleColor: "blue",
      clothing: "dressShirt",
      clothingColor: "red",
      eyebrows: "angry",
      eyes: "happy",
      faceMask: true,
      faceMaskColor: "green",
      facialHair: "none3",
      graphic: "vue",
      hair: "bob",
      hairColor: "pink",
      hat: "turban",
      hatColor: "green",
      lashes: true,
      lipColor: "pink",
      mask: true,
      mouth: "tongue",
      skinTone: "light",
    },
  },
  {
    id: 4,
    content: {
      accessory: "none",
      body: "breasts",
      circleColor: "blue",
      clothing: "vneck",
      clothingColor: "red",
      eyebrows: "raised",
      eyes: "happy",
      faceMask: true,
      faceMaskColor: "white",
      facialHair: "none",
      graphic: "react",
      hair: "long",
      hairColor: "pink",
      hat: "none",
      hatColor: "white",
      lashes: true,
      lipColor: "green",
      mask: true,
      mouth: "serious",
      skinTone: "light",
    },
  },
  {
    id: 5,
    content: {
      accessory: "shades",
      body: "chest",
      circleColor: "blue",
      clothing: "vneck",
      clothingColor: "black",
      eyebrows: "raised",
      eyes: "normal",
      faceMask: true,
      faceMaskColor: "white",
      facialHair: "none3",
      graphic: "none",
      hair: "balding",
      hairColor: "white",
      hat: "none",
      hatColor: "white",
      lashes: true,
      lipColor: "red",
      mask: true,
      mouth: "openSmile",
      skinTone: "red",
    },
  },
];
